name: peopeo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  fluttertoast: ^4.0.1
  file_picker: ^1.1.1
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.4.1
  http: ^0.12.0+4
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.13.0+1
  google_sign_in: ^4.1.1
  cupertino_icons: ^0.1.2
  cached_network_image: 2.0.0-rc.1
  shared_preferences: ^0.5.3+4
  image_picker: ^0.6.1+8
  firebase_storage: ^3.0.6
  photo_view: ^0.5.0
  flutter_facebook_login: ^3.0.0
  side_header_list_view: ^0.0.4
  uuid: ^2.0.4
  flutter_rating_bar: ^3.0.1+1
  path_provider: ^1.6.1
  video_thumbnail: ^0.2.0
  video_player: ^0.10.8+1
  firebase_messaging: ^6.0.12
  badges: ^1.1.1
  json_serializable: ^3.2.5
  flutter_native_timezone: ^1.0.4
  flutter_webview_plugin: ^0.3.10+1
  webview_flutter: ^0.3.19+9
  date_format: ^1.0.8
  intl: ^0.16.1
  flutter_web_browser: ^0.11.0
  receive_sharing_intent: ^1.4.0+2
  share: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
    - assets/images/mimi1.gif
    - assets/images/mimi2.gif
    - assets/images/mimi3.gif
    - assets/images/mimi4.gif
    - assets/images/mimi5.gif
    - assets/images/mimi6.gif
    - assets/images/mimi7.gif
    - assets/images/mimi8.gif
    - assets/images/mimi9.gif
    - assets/images/app_logo.jpeg
  fonts:
    - family: Armata
      fonts:
        - asset: assets/fonts/Armata-Regular.ttf